const teams = {
  AFGHANISTAN: "AFGHANISTAN",
  AUSTRALIA: "AUSTRALIA",
  BANGLADESH: "BANGLADESH ",
  ENGLAND: "ENGLAND",
  INDIA: "INDIA",
  NETHERLANDS: "NETHERLANDS",
  NEW_ZEALAND: "NEW ZEALAND",
  PAKISTAN: "PAKISTAN",
  SOUTH_AFRICA: "SOUTH AFRICA",
  SRI_LANKA: "SRI LANKA",
};

module.exports = { teams }